const products = [
  {
    id: "AAAAAAAAA00000001",
    name: "Acacia pycnantha",
    commonName: "Golden Wattle",
    directory: "/images/plants/Acacia_pycnantha/",
    small_image: "shutterstock_611904872_1.jpg",
    large_image: "shutterstock_1544034050_1.jpg",
    price: "44.99",
    details:
      "Discover the beauty of the Acacia pycnantha, also known as the golden wattle, a stunning tree from the Fabaceae family, native to southeastern Australia. This tree can reach a height of up to 8 m (26 ft) and has unique phyllodes (flattened leaf stalks) that replace traditional leaves. These sickle-shaped phyllodes are between 9 and 15 cm (3+1⁄2 and 6 in) long, and 1–3.5 cm (1⁄2–1+1⁄2 in) wide, giving the tree an impressive appearance. In late winter and spring, the tree is adorned with a profusion of fragrant, golden flowers, which are followed by long seed pods. These beautiful flowers are cross-pollinated by several species of honeyeater and thornbill, who visit the phyllodes' nectaries and brush against the flowers, transferring pollen between them. This tree is commonly found as an understorey plant in eucalyptus forests and can be found from southern New South Wales and the Australian Capital Territory, through Victoria, and into southeastern South Australia. Add this stunning tree to your collection today and enjoy its beauty in your garden!",
    link: "https://en.wikipedia.org/wiki/Acacia_pycnantha",
    // loacation:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Acacia_pycnanthaDistMap739.png/440px-Acacia_pycnanthaDistMap739.png",
    location: "map.jpg",
    sunLight: "Full sun",
    discountPercent : 25,
    new: true,
  },
  {
    id: "AAAAAAAAA00000002",
    name: "Angophora costata",
    commonName: "Smooth Barked Apple",
    directory: "/images/plants/Angophora_costata/",
    small_image: "shutterstock_1415738750_1.jpg",
    large_image: "shutterstock_1595770927_1.jpg",
    price: "189.99",
    details:
      "Introducing the magnificent Angophora costata, also known as the Sydney red gum, rusty gum, or smooth-barked apple, a stunning tree species endemic to eastern Australia. With a maximum height of 30 m (100 ft), this species is easily recognizable thanks to its distinctive smooth bark, which is pinkish or orange-brown when new and fades to a beautiful grey with age. Its lance-shaped leaves are arranged in opposite pairs along the stems, providing a gorgeous texture to the tree. From October to December, white or creamy white flowers appear, adding a pop of brightness to the tree's appearance. The flower buds are usually arranged in groups of three, followed by ribbed, oval, or bell-shaped fruit. Add this impressive species to your garden today and enjoy its beauty for years to come!",
    link: "https://en.wikipedia.org/wiki/Angophora_costata",
    // location:"https://upload.wikimedia.org/wikipedia/commons/6/69/Angophora_costata_DistMap.png",
    location: "map.jpg",
    sunLight: "Full sun",
    discountPercent : 0,
    new: false,
  },
  {
    id: "AAAAAAAAA00000003",
    name: "Anigozanthos flavidus",
    commonName: "Evergreen Kangaroo Paw",
    directory: "/images/plants/Anigozanthos_flavidus/",
    small_image: "shutterstock_390107410_1.jpg",
    large_image: "shutterstock_1788084995_1.jpg",
    price: "18.95",
    details:
      "Bring a touch of Southwest Australia to your garden with the Anigozanthos flavidus, commonly known as the tall, yellow, or evergreen kangaroo paw. This stunning plant, a member of the Haemodoraceae family, boasts beautiful yellow flowers, which inspired its specific epithet, flavidus. The Anigozanthos genus, which includes kangaroo and cats' paws, produces an evergreen clump of strap-like leaves up to 1 metre long and 0.2 m wide, growing from an underground rhizome around 0.5 m in diameter. This remarkable species can regenerate after drought or fire thanks to its rhizome. During the summer, the plant produces over 350 flowers on up to 10 long stems. These flowers, frequently yellow and green, may present in shades of red, pink, orange, or brown, making them a vibrant addition to any garden. Birds help distribute pollen by plunging into the flowers to reach the nectaries. The plant is commonly found along roadsides, along creeks, and in forests and swamps, and other unshaded winterwet habitat. Add the Anigozanthos flavidus to your garden today and enjoy the beauty and unique characteristics of this stunning plant.",
    link: "https://en.wikipedia.org/wiki/Anigozanthos_flavidus",
    // location:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Anigozanthos_flavidus_Haemodoraceae6.png/440px-Anigozanthos_flavidus_Haemodoraceae6.png",
    location: "map.jpg",
    sunLight: "Full sun/ Partial sun",
    discountPercent : 10,
    new: true,
  },
  {
    id: "AAAAAAAAA00000004",
    name: "Boronia serrulata",
    commonName: "Native Rose/ Rose Boronia",
    directory: "/images/plants/Boronia_serrulata/",
    small_image: "shutterstock_1181054476_1.jpg",
    large_image: "shutterstock_1185578461_1.jpg",
    price: "56.60",
    details:
      "Boronia serrulata is a charming woody shrub that can grow up to 1.5 m (4.9 ft) tall, and has smooth branchlets. Its leaves are simple, broadly egg-shaped with fine teeth at the edges, and are 6-18 mm (0.24-0.71 in) long and 1.5-9 mm (0.059-0.354 in) wide, making them appear crowded. The shrub produces up to seven cup-shaped flowers that grow at the ends of the branchlets on a peduncle up to 3.5 mm (0.14 in) long. The flowers are either sessile or on a pedicel up to 3.5 mm (0.14 in) long, and each has four pink petals that are 6-11 mm (0.24-0.43 in) long. The flowering season is from August to November, and the fruit is a small, mostly smooth capsule that is about 4 mm (0.16 in) long and 2 mm (0.079 in) wide.",
    link: "https://en.wikipedia.org/wiki/Boronia_serrulata",
    // location:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Boronia_serrulata_DistMap110.png/440px-Boronia_serrulata_DistMap110.png",
    location: "map.jpg",
    sunLight: "Full sun to Full shade",
    discountPercent : 0,
    new: false,
  },
  {
    id: "AAAAAAAAA00000005",
    name: "Callistemon citrinus",
    commonName: "Scarlett Bottlebrush",
    directory: "/images/plants/Callistemon_citrinus/",
    small_image: "shutterstock_81971158_1.jpg",
    large_image: "shutterstock_1774816355_1.jpg",
    price: "110.00",
    details:
      "At our plant sale, you can find a wide variety of Callistemon species, known for their distinctive bottlebrush-shaped flowers that resemble a traditional bottle brush. These plants are primarily found in the temperate regions of Australia, particularly along the east coast, and thrive in moist conditions. However, some species are also drought-resistant and can be used in ornamental landscaping around the world. Whether you're looking for a beautiful addition to your garden or a unique gift for a friend, our selection of Callistemon species is sure to impress.",
    link: "https://en.wikipedia.org/wiki/Callistemon",
    // location:"https://anpsa.org.au/wp-content/uploads/Callistemon-citrinus.gif",
    location: "map.jpg",
    sunLight: "Full sun",
    discountPercent : 10,
    new: false,
  },
  {
    id: "AAAAAAAAA00000006",
    name: "Correa federation bell x mannii",
    commonName: "Native Fuchsia",
    directory: "/images/plants/Correa_federation_bell_x_mannii/",
    small_image: "shutterstock_1711478590_1.jpg",
    large_image: "shutterstock_1716199645_1.jpg",
    price: "16.98",
    details:
      "Looking for a beautiful and easy-to-grow plant that will attract birds to your garden? Look no further than Correa Federation Bell, also known as Native Fuchsia. With its lovely bell-shaped flowers and varying foliage, this plant is a stunning addition to any garden, perfect for cottage gardens, informal hedges, and containers or pots. The two-toned pale yellow and pale pink flowers bloom in autumn to winter, adding color to your garden throughout the colder months. Correa Federation Bell is generally easy to grow and can tolerate coastal areas. To maintain its bushiness, simply tip prune and fertilize annually with a long-term slow-release fertilizer. With a height and width of 1.5m, this plant is sure to make a statement in your garden.",
    link: "https://en.wikipedia.org/wiki/Correa_(plant)",
    // location:"https://wtlandcare.org/wp-content/uploads/2016/01/correa-reflexa-var-reflexa-flora-location-map.png",
    location: "map.jpg",
    sunLight: "Partial sun",
    discountPercent : 0,
    new: false,
  },
  {
    id: "AAAAAAAAA00000007",
    name: "Corymbia ficifolia",
    commonName: "Red Flowering Gum",
    directory: "/images/plants/Corymbia_ficifolia/",
    small_image: "shutterstock_1308004495_1.jpg",
    large_image: "shutterstock_1611871573_1.jpg",
    price: "229.99",
    details:
      "Corymbia ficifolia, also known as the Red Flowering Gum, is a stunning tree that can grow up to 10 m (33 ft) tall. Its rough, fibrous bark gives it a unique look and adds character to any landscape. In the summer months, the tree produces bright red to pink or orange bell-shaped flowers that attract bees, butterflies and nectar-feeding birds. The leaves are egg-shaped to broadly lance-shaped, and its flowers are arranged on the ends of the branches. This tree is easy to grow and requires minimal maintenance. It can tolerate a wide range of soil types and is drought-resistant once established. The Red Flowering Gum is an excellent choice for any garden, park or street planting.",
    link: "https://en.wikipedia.org/wiki/Corymbia_ficifolia",
    location: "map.jpg",
    sunLight: "Full sun/ Partial sun",
    discountPercent : 30,
    new: false,
  },
  {
    id: "AAAAAAAAA00000008",
    name: "Eucalyptus caesia",
    commonName: "Gum Tree",
    directory: "/images/plants/Eucalyptus_caesia/",
    small_image: "shutterstock_144993751_1.jpg",
    large_image: "shutterstock_144993766_1.jpg",
    price: "149.99",
    details:
      "Eucalyptus caesia, also known as Silver Princess, is a beautiful mallee tree that grows up to 14 meters tall and has a lignotuber. Its bark is smooth reddish-brown at first, shedding in curling longitudinal flakes called 'minnirichi'. The young branches are shiny red, covered with a waxy, bluish-white bloom. Young plants and coppice regrowth have thick, glossy green heart-shaped leaves, while adult leaves are lance-shaped to curved with a petiole. Its flower buds, arranged in groups of three, bloom from May to September, producing pink stamens with yellow tips. The woody bell-shaped or urn-shaped capsule fruit is around 15-25 mm long and 18-23 mm wide on a peduncle 13-33 mm long. Eucalyptus caesia is a stunning addition to any garden, and will surely be a conversation starter.",
    link: "https://en.wikipedia.org/wiki/Eucalyptus_caesia",
    // location:"https://en.wikipedia.org/wiki/File:E._caesia.JPG",
    location: "map.jpg",
    sunLight: "Full sun",
    discountPercent : 0,
    new: true,
  },
  {
    id: "AAAAAAAAA00000009",
    name: "Eucalyptus pauciflora",
    commonName: "Snow Gum",
    directory: "/images/plants/Eucalyptus_pauciflora/",
    small_image: "shutterstock_1582478977 (1)_1.jpg",
    large_image: "shutterstock_1114744187_1.jpg",
    price: "310.00",
    details:
      "Eucalyptus pauciflora is a majestic tree or mallee that can reach a height of 20 to 30 meters (66 to 98 feet) and produces a lignotuber. Its smooth bark ranges from white to grey or yellow and peels off in long strips, sometimes showing insect scribbles. Young plants and regrowth have bluish-green or glaucous, broadly lance-shaped to egg-shaped leaves that measure between 44 and 170 mm (1.7 to 6.7 inches) in length and 20 to 85 mm (0.79 to 3.35 inches) in width. Adult leaves are glossy green on both sides, lance-shaped to curved or elliptical, 60 to 200 mm (2.4 to 7.9 inches) in length and 12 to 50 mm (0.47 to 1.97 inches) in width, and taper to a petiole measuring between 8 and 33 mm (0.31 to 1.30 inches) in length. The flower buds grow in clusters of seven to fifteen, sometimes more, in the leaf axils on an unbranched peduncle that is 3 to 15 mm (0.12 to 0.59 inches) long, with each bud on a pedicel that can reach up to 6 mm (0.24 inches) in length. The mature buds are oval, measuring 4 to 8 mm (0.16 to 0.31 inches) in length and 3 to 5 mm (0.12 to 0.20 inches) in width, with a conical to rounded operculum. Flowering occurs from October to February and the flowers are white. The fruit is a woody capsule that can be cup-shaped, conical, or hemispherical and measures 5 to 11 mm (0.20 to 0.43 inches) in length and width.",
    link: "https://en.wikipedia.org/wiki/Eucalyptus_pauciflora",
    // location:"https://wtlandcare.org/wp-content/uploads/2016/01/eucalyptus-pauciflora-flora-location-map.png",
    location: "map.jpg",
    sunLight: "Full sun",
    discountPercent : 30,
    new: false,
  },
  {
    id: "AAAAAAAAA00000010",
    name: "Grevillea alpina x rosmarinifolia",
    commonName: "Alpine Grevillea/ Cat's Claws",
    directory: "/images/plants/Grevillea_alpina_x_rosmarinifolia/",
    small_image: "shutterstock_1463973167_1.jpg",
    large_image: "shutterstock_1418845589_1.jpg",
    price: "92.95",
    details:
      "Grevillea alpina x rosmarinifolia is a highly variable species, with variations in form, leaves, and flowers. These plants can reach a height of 0.3 to 2 meters (0.98 to 6.56 ft). The leaves may be linear, oblong, or elliptic and are typically 0.5 to 2 centimeters (0.20 to 0.79 in) long and 1.5 to 4 millimeters (0.059 to 0.157 in) wide, with or without hairs on both surfaces. The edges of the leaves may be curved backwards or revolute. The flowers are highly variable in color, ranging from red, orange, pink, yellow, or cream, with commonly seen red-yellow or red-cream combinations. These beautiful flowers bloom primarily from August to December in their native range. The fruits are hairy, leathery, ovoid follicles that are 8.5 to 12 millimeters (0.33 to 0.47 in) long, which split open to release winged seeds. Get yours today and add a pop of color to your garden!",
    link: "https://en.wikipedia.org/wiki/Grevillea_alpina",
    // location:"https://anpsa.org.au/wp-content/uploads/Grevillea-alpina.gif",
    location: "map.jpg",
    sunLight: "Full sun/ Partial sun",
    discountPercent : 0,
    new: true,
  },
  {
    id: "AAAAAAAAA00000011",
    name: "Grevillia robusta",
    commonName: "Southern Silky Oak",
    directory: "/images/plants/Grevillia_robusta/",
    small_image: "shutterstock_1788006386_1.jpg",
    large_image: "shutterstock_514124533_1.jpg",
    price: "162",
    details:
      "Grevillea robusta is a stunning, evergreen tree with a single main trunk that can grow between 5-40 m (20-100 ft) tall. The dark grey, furrowed bark adds to its distinctive appearance. The fern-like leaves, which are between 10-34 cm (4-10 in) long and 9-15 cm (4-6 in) wide, have between 11 and 31 main lobes, each of which can be further divided into as many as four narrow, linear triangular shapes. Before flowering, the tree loses many of its leaves, which makes the flowers stand out even more. The flowers, which bloom from September to November, are arranged in one-sided, 'toothbrush'-like groups, sometimes branched, and are mostly yellowish orange, or sometimes reddish. The fruit that follows is a glabrous follicle. This fast-growing tree would make a fantastic addition to any native garden.",
    link: "https://en.wikipedia.org/wiki/Grevillea_robusta",
    // location:"https://anpsa.org.au/wp-content/uploads/G-robusta.gif",
    location: "map.jpg",
    sunLight: "Full sun",
    discountPercent : 0,
    new: false,
  },
  {
    id: "AAAAAAAAA00000012",
    name: "Hardenbergia violacea",
    commonName: "False Sarsaparilla",
    directory: "/images/plants/Hardenbergia_violacea/",
    small_image: "shutterstock_1791808445_1.jpg",
    large_image: "shutterstock_1675721635_1.jpg",
    price: "15.99",
    details:
      "Hardenbergia violacea, or Purple Coral Pea, is a versatile sub-shrub that can grow prostrate or climb up to 2m. It has egg-shaped to lance-shaped leaves and stunning flowers in purple, pink, white, and other hues. The flowers bloom from August to November and are arranged in racemes of 20-40 blooms. After flowering, it produces a pod with 6-8 seeds. It regrows from its roots after a fire and was used experimentally as a substitute for sarsaparilla. Our locally grown Hardenbergia violacea plants are perfect for adding color and texture to your garden. Order now and enjoy the beauty and resilience of this remarkable native plant.",
    link: "https://en.wikipedia.org/wiki/Hardenbergia_violacea",
    // location:"https://anpsa.org.au/wp-content/uploads/h-vio.gif",
    location: "map.jpg",
    sunLight: "Full sun/ Partial sun",
    discountPercent : 20,
    new: false,
  },
  {
    id: "AAAAAAAAA00000013",
    name: "Poa labillardierei",
    commonName: "Tussock-grass",
    directory: "/images/plants/Poa_labillardierei/",
    small_image: "shutterstock_374910508_1.jpg",
    large_image: "shutterstock_1791619955_1.jpg",
    price: "7.14",
    details:
      "This dense, tufting native perennial is a showstopper in any landscape. With blue-grey foliage that grows up to 1m x 1m wide, this plant is a hardy addition to your garden. In Spring and throughout Summer, green-purple clustered spikelets of inflorescences emerge, adding a pop of color to your outdoor space. This versatile plant is perfect for coastal sites, where it can withstand harsh winds and salt spray, making it an excellent choice for erosion control. It is also well-suited for use in urban or commercial landscapes, where its low maintenance requirements and attractive appearance make it a popular choice among gardeners and landscapers.",
    link: "https://en.wikipedia.org/wiki/Poa_labillardierei",
    // location:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQD99mKkghXKxBV6515WUIbn69-dcgCKre_MA&usqp=CAU",
    location: "map.jpg",
    sunLight: "Full sun/ Partial sun",
    discountPercent : 0,
    new: false,
  },
  {
    id: "AAAAAAAAA00000014",
    name: "Syzygium smithii",
    commonName: "Lilly Pilly",
    directory: "/images/plants/Syzygium_smithii/",
    small_image: "shutterstock_1720832230 (1)_1.jpg",
    large_image: "shutterstock_1735075418_1.jpg",
    price: "39.99",
    details:
      "Syzygium smithii, also known as Lilly Pilly, is a majestic tree that can reach up to 20 m (66 ft) high by 5-15 m (16-49 ft) wide, with a trunk that can grow up to 70 cm (2.3 ft) in diameter. This tree is a stunning addition to any landscape, with glossy green leaves that shimmer in the sunlight. One of the largest specimens of this tree was recorded at Dingo Creek Flora Reserve, south of Tenterfield. It stood at an impressive 30 m (98 ft) tall and had a trunk that measured 60 cm (2.0 ft) in diameter. At our native plant sale, you can find a selection of Syzygium smithii plants that are perfect for adding shade, beauty, and privacy to your garden. Our plants are locally grown and well-adapted to the climate of our region, ensuring that they will thrive in your landscape. Order now and enjoy the many benefits of this remarkable native species",
    link: "https://en.wikipedia.org/wiki/Syzygium_smithii",
    // location:"https://anpsa.org.au/wp-content/uploads/a-smi.gif",
    location: "map.jpg",
    sunLight: "Full sun/ Partial sun",
    discountPercent : 10,
    new: false,
  },
  {
    id: "AAAAAAAAA00000015",
    name: "Telopea speciosissima",
    commonName: "New South Wales Waratah",
    directory: "/images/plants/Telopea_speciosissima/",
    small_image: "shutterstock_1268838721_1.jpg",
    large_image: "shutterstock_639385780_1.jpg",
    price: "5.25",
    details:
      "The New South Wales waratah, also known as Telopea speciosissima, is a magnificent large shrub that belongs to the Proteaceae family. This shrub is endemic to New South Wales, Australia, and is the state's floral emblem. At our native plant sale, you can find a selection of T. speciosissima plants that are locally grown and perfect for adding a touch of natural beauty to your landscape. This shrub grows to a height of 3 to 4 m (9.8 to 13.1 ft) and has a spread of 2 m (6.6 ft), with dark green leaves that provide an excellent backdrop for the shrub's stunning inflorescences. The waratah's flowerheads, which appear in spring, are a striking shade of red and contain hundreds of individual flowers, making them a favourite of pollinators such as honeyeaters and various insects. The New South Wales waratah is also famous for being a food source for the eastern pygmy possum, which is a rare and delightful native marsupial. This species is also hardy and adaptable, making it an excellent choice for a wide range of gardens and landscapes. Order your T. speciosissima plants now and enjoy the beauty of this remarkable native shrub.",
    link: "https://en.wikipedia.org/wiki/Telopea_speciosissima",
    // location:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Telopea_speciosissima_dist_map.png/440px-Telopea_speciosissima_dist_map.png",
    location: "map.jpg",
    sunLight: "Semi-Shaded",
    discountPercent : 0,
    new: true,
  },
];

export default products;
